import matplotlib.pyplot as plt
from IPython import display

plt.ion()

def plot(scores, mean_scores, aux01):
    display.clear_output(wait=True)
    display.display(plt.gcf())
    plt.clf()
    plt.title('Business Intelligent...')
    plt.xlabel('01--> blue  02--> Orange  03--> Green ')
    plt.ylabel('.... ')
    plt.plot(scores)
    plt.plot(mean_scores)
    plt.plot(aux01)
    plt.ylim(ymin=0)
    plt.text(len(scores)-1, scores[-1], str(scores[-1]))
    plt.text(len(mean_scores)-1, mean_scores[-1], str(mean_scores[-1]))
    plt.show(block=False)
    plt.pause(.1)
def plot2(scores, mean_scores, aux01):
    display.clear_output(wait=True)
    display.display(plt.gcf())
    plt.clf()
    plt.title('2 Business Intelligent...')
    plt.xlabel('01--> blue  02--> Orange  03--> Green ')
    plt.ylabel('.... ')
    plt.plot(scores)
    plt.plot(mean_scores)
    plt.plot(aux01)
    plt.ylim(ymin=0)
    plt.text(len(scores)-1, scores[-1], str(scores[-1]))
    plt.text(len(mean_scores)-1, mean_scores[-1], str(mean_scores[-1]))
    plt.show(block=False)
    plt.pause(.1)
